experiment_name: 'bert icd'
num_gpu: 1                         # GPU数量
device_id: '0'
visual_device: '0'
main_device_id: '0'
resume_path: null                         # path to latest checkpoint


# 模型
model_arch:
  type: 'LMNER'
  args:
    transformer_model: 'voidful/albert_chinese_tiny'
    is_train: true

data_set:
  type: 'LMDataset'
  args:
    data_dir: 'data/chinese_medical_ner'
    file_name: 'train.jsonl'
    data_mode: 'train_valid'                                       # mode:train valid test train_valid
    transformer_model: 'voidful/albert_chinese_tiny'
    valid_size: 0.3
    shuffle: true
    overwrite_cache: true

train_loader:
  type: 'DataLoader'
  args:
    batch_size: 16
    num_workers: 12

valid_loader:
  type: 'DataLoader'
  args:
    batch_size: 32
    num_workers: 12

optimizer:
  type: 'AdamW'
  args:
    amsgrad: false

lr_scheduler:
  type: 'get_linear_schedule_with_warmup'
  args:
    num_warmup_steps: 3


trainer:
  epochs: 100
  save_dir: 'saved/'
  save_period: 3
  verbosity: 2
  monitor: "min val_loss"
  early_stop: 20
  tensorboard: true

